account/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('company_profile', views.companyProfile, name='company_profile'),
    path('company_profile/<int:id>',views.editcompany, name='editcompany'),
    path('profile', views.profile, name='profile'),
    path('profile/<int:id>',views.editprofile, name='edit')
]

jobboard/urls.py
from django.urls import path, include,reverse
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name='post'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:pk>/', views.post_detail, name="post_detail"),
    path('list_app/<int:pk>/', views.list_app, name='list_app'),
    path('about', views.about, name='about'),
    path('contact/', views.contact , name='contact'),
    path('createPost',views.createPost, name='createPost'),
    path('update_post/<str:pk>/', views.updatePost, name="update_post"),
    path('delete_post/<str:pk>/', views.deletePost, name="delete_post"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('jobboard.urls')),
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
]
if settings.DEBUG:
    if settings.DEBUG:     
        urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT) 
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/application.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


  <!-- HOME -->
  <section class="section-hero overlay inner-page bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class="text-white font-weight-bold"></h1>
          <div class="custom-breadcrumbs">
            <a href="#">Home</a> <span class="mx-2 slash">/</span>
            
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="site-section">{% if user.is_authenticated %}
    <div class="container">
      <form  enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-lg-3">
          <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <img class="border p-1 d-inline-block rounded-circle" src="{{user.profile.image.url}}" width="200" height="200">&nbsp;&nbsp;
              <br> <br>
            <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Profile</a>
            <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Manage Job</a>
          </div>
        </div>

   
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>KRADAN IT</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Free-Template.co" />
    <link rel="shortcut icon" href="ftco-32x32.png">
  
    
    <link href="https://fonts.googleapis.com/css?family=Athiti&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/quill.snow.css' %}">
    

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">    
 
  </head>
  <body id="top">


    

<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    

    <!-- NAVBAR -->
    <header class="site-navbar mt-3">
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="site-logo col-6"><a href="{% url 'post:index' %}">Kradan IT</a></div>

          <nav class="mx-auto site-navigation">
            <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
              <li><a href="{% url 'post:index' %}" class="nav-link active">Home</a></li>
              <li><a href="{% url 'post:about' %}">About</a></li>
             
              {% if user.is_authenticated%}
              <li class="has-children">
                <a href="">Employment</a>
                <ul class="dropdown">
                  <li><a href="{% url 'company_profile' %}">Manage Company</a></li>
                  <li><a href="{% url 'post:createPost'%}">Add a new job</a></li>
                </ul>
              </li>   
              {% endif %}          
              <li><a href="{% url 'post:contact' %}">Contact us</a></li>
              <li class="d-lg-none"><a href="{% url 'register' %}">Register</a></li>
              <li class="d-lg-none"><a href="{% url 'login' %}">Log in</a></li>
            </ul>
          </nav>

          {% if user.is_authenticated %}
          <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
            <div class="ml-auto"></div>
            <a href="{% url 'profile' %}" class="btn btn-primary  text-white btn-user"><span class="icon-user icon mr-2"></span>Hello.. {{user.username}}</a>&nbsp;&nbsp;
            <a href="{% url 'logout' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Log out</a>
          {% else %}
          <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
            <div class="ml-auto">
              <a href="{% url 'register' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Register</a>
              <a href="{% url 'login' %}" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Log in</a>
            </div>
          {% endif %}
            <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
          </div>

        </div>
      </div>
    </header>
    {% block content %}

    {% endblock %}
      
      <!-- SCRIPTS -->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
      <script src="{% static 'js/stickyfill.min.js' %}"></script>
      <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
      
      
     
      
      <script src="{% static 'js/bootstrap-select.min.js' %}"></script>
      <script src="{% static 'js/quill.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>    
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}

 <section class="section-hero overlay inner-page bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">
  </section>


    <section class="site-section" id="next-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-8 ">
          <div class="col-8 text" data-aos="fade">
            <h2 class="section-title mb-3">Contact Us</h2>
          </div>
            <form action="#" class="">

             <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15840.0973215834!2d100.49047308356327!3d7.006417819417457!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x304d29af97c3cdef%3A0xf7efa93203415043!2z4Lih4Lir4Liy4Lin4Li04LiX4Lii4Liy4Lil4Lix4Lii4Liq4LiH4LiC4Lil4Liy4LiZ4LiE4Lij4Li04LiZ4LiX4Lij4LmM!5e0!3m2!1sth!2sth!4v1588244108415!5m2!1sth!2sth" 
             width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
  
            </form>
          </div>
          <div class="col-lg-5 ml-auto">
            <div class="p-4 mb-3 bg-white">
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">เรื่อนศรีทรัพย์แมนชั่น เลขที่4 หมู่6 ถนนทุ่งรี ซอย3 ตำบลคอหงส์ อำเภอเมือง จังหวัดสงขลา </p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#">youremail@domain.com</a></p>

            </div>
          </div>
        </div>
      </div>
    </section>

   

  </body>
</html>
{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}


<section class="section-hero overlay inner-page bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <h1 class="text-white font-weight-bold">Dashboard</h1>
          <div class="custom-breadcrumbs">
            <a href="#">Home</a> <span class="mx-2 slash">/</span>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="site-section">
    <div class="container">

        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2">Manage Jobs</h2>
          </div>
        </div>

	
      <table class="table table-hover">
        <thead>
				<tr>
					<th>title</th>
          <th>Type_Job</th>
          <th>Date_posted</th>
          <th>Manage</th>
          <th></th>
        </tr>
      </thead>
                {% for i in post %}
					<tr>
						<td>{{i.title}}</td>
            <td>{{i.type_job}}</td>
            <td>{{i.date_posted|date:"F d, Y"}}</td>
                
						<td> <a class="btn btn-sm btn" href="{% url 'post:update_post' i.id %}">
              <i class="icon-cog"></i> Edit</a></td>

						<td><a class="btn btn-sm btn-danger" href="{% url 'post:delete_post' i.id %}">Delete</a></td>

					</tr>
				{% endfor %}
      </table>
      <a class="btn btn-primary  btn-sm btn-block" href="{% url 'post:createPost' %}">Create Post</a>
		</div>
  </div> 
</div>
 </section>

{% endblock %}

templates/delete.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>KRADAN IT</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Free-Template.co" />
    <link rel="shortcut icon" href="ftco-32x32.png">

    <link href="https://fonts.googleapis.com/css?family=Athiti&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/quill.snow.css' %}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">    
  </head>
<body>
<br>
<div class="row">
	<div class="col-md-12">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item}}"?</p>

			<form action="{% url 'post:delete_post' item.id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'company_profile' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Confirm" value="Confirm">
			</form>
		</div>
	</div>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<style>
input[type=text], select {
  width: 23%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
</style>

<!-- HOME -->
    <section class="home-section section-hero overlay bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-12">
            <div class="mb-5 text-center">
              <h1 class="text-white font-weight-bold">IT JOBS BOARD</h1>
              <p>At Sountern</p>
            </div>
            <form method="get" class="search-jobs-form">
              <p>Location {{myFilter.form.location}}    Salary{{myFilter.form.salary}}  JobType{{myFilter.form.type_job}} 
            
    
              <button type="submit" class="btn btn-primary "><span class="icon-search icon mr-2"></span>Find Job</button>
            </form>
          </div>
        </div>
      </div>

      <a href="#next" class="scroll-button smoothscroll">
        <span class=" icon-keyboard_arrow_down"></span>
      </a>

    </section>
    
    
    <section class="site-section">
      <div class="container">

        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2">{{ post.count }} Job Listed</h2>
          </div>
        </div>
        {% for i in post %}
        <ul class="job-listings mb-5">
          <li class="job-listing d-block d-sm-flex pb-3 pb-sm-0 align-items-center">
            <a href="{% url 'post:post_detail' i.id  %}"></a>
            <div class="job-listing-logo"> {% if i.user == user %}
              <img class="border p-1 d-inline-block rounded" src="{{user.companyprofile.com_img.url}}" width="200" height="200">
              {% else %} 
              <img class="border p-1 d-inline-block rounded" src="{{i.user.companyprofile.com_img.url}}" width="200" height="200">    
              {% endif %}
            </div>

            <div class="job-listing-about d-sm-flex custom-width w-100 justify-content-between mx-4">
              <div class="job-listing-position custom-width w-50 mb-3 mb-sm-0">
                <h2>{{ i.title }} </h2>
                <span>เงินเดือน : {{ i.salary }}</span>
              </div>
              <div class="job-listing-location mb-3 mb-sm-0 custom-width w-25">
                <span class="icon-room"></span>{{ i.date_posted|date:"F d, Y"}}<br>
                <h6 class="text-danger"> {{ i.timestamp|timesince }} ago</h6>
              </div>
              <div class="job-listing-meta">
                <span class="badge badge-danger">{{ i.type_job }}</span>
              </div>
              <div class="job-listing-meta">
                <span class="badge badge-primary">{{ i.location }}</span>
              </div>
            </div>
          </li>
          {% endfor %}
      
      
    </section>
    

    <section class="site-section services-section bg-light block__62849" id="next-section">
      <div class="container">
        
        
       
        </div>
      </div>
    </section>
  </body>
</html>
{% endblock %}

templates/list_app.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block content %}
<link href="https://fonts.googleapis.com/css?family=Prompt&display=swap" rel="stylesheet">

<style>
h1 {
  font-family: Prompt ;
}

</style>

 <!-- HOME -->
  <section class="section-hero overlay inner-page bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">
  </section>

 <section class="site-section">
    <div class="container">

      <div class="row align-items-center mb-5">
        <div class="col-lg-8 mb-4 mb-lg-3">
          <div class="d-flex align-items-center">
            <div>
              <h2>{{posts.title}}</h2>
            </div>
          </div>
        </div>
              <table class="table table-bordered ">
                  <thead>
                  <tr>
                    <th>#</th>
                    <th>Applicant(Name)</th>
                    <th>Applicant(Lastname)</th>
                    <th>Date_Apply</th>
                    <th>Resume</th>
                    <th>Contact</th>
                    
                  </tr>
                </thead>
                {% if posts.user.id == user.id %}{% if posts.post %}
                  {% for applicant in posts.post.all %}
                  <tr>
                      <td>{{ forloop.counter}}</td>
                      <td>{{ applicant.applicant.first_name }}</td>
                      <td>{{ applicant.applicant.last_name }}</td>
                      <td>{{ applicant.date_applied}}</td>
                      <td><a href="{{ applicant.applicant.profile.resume.url}}" class="btn btn-primary btn-sm">Resume</a></td>
                      <td>{{ applicant.contact_app}}</td>
                        
                  </tr>{% endfor %}{% endif %}
                  {% else %}
                  No Applicant

                {% endif %}
                </table>
            
                </div>
            </div>
        </div>
    </div>
</section>
  {% endblock %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
<style>
.modal-header {
    position: relative;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -ms-flex-direction: column;
    flex-direction: column;
    width: 100%;
    pointer-events: auto;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid rgba(0, 0, 0, 0.1);
    border-radius: 0.3rem;
    outline: 0;
}
.modal-body {
    position: relative;
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -ms-flex-direction: column;
    flex-direction: column;
    width: 100%;
    pointer-events: auto;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid rgba(0, 0, 0, 0.1);
    border-radius: 0.3rem;
    outline: 0;
}
</style>
 <section class="section-hero overlay inner-page bg-image" style="background-image: url('static/images/hero_1.jpg');" id="home-section">
  </section>

    <section class="site-section">
      <div class="container">
        <div class="row align-items-center mb-5">
          <div class="col-lg-8 mb-4 mb-lg-0">
            <div class="d-flex align-items-center">
              <div class="border p-2 d-inline-block mr-3 rounded-circle">{% if posts.user == user %}
                <img class="rounded-circle " src="{{user.companyprofile.com_img.url}}" width="200" height="200">
                {% else %} 
                <img class="rounded-circle " src="{{posts.user.companyprofile.com_img.url}}" width="200" height="200">
                {% endif %}
              </div>
              <div>
                <h2>{{ posts.title }}</h2>
              <div>{% if posts.user == user %}
                  <span class="ml-0 mr-2 mb-2"><span class="icon-briefcase mr-2"></span>{{user.companyprofile.company_name}}</span>
                  {% else %} 
                  <span class="ml-0 mr-2 mb-2"><span class="icon-briefcase mr-2"></span>{{posts.user.companyprofile.company_name}}</span>
                  {% endif %}
                  <span class="m-2"><span class="icon-room mr-2"></span>{{ posts.date_posted|date:"F d, Y"}}</span>
                  <span class="m-2"><span class="icon-clock-o mr-2"></span><span class="text-primary">{{ posts.timestamp|timesince }} ago</span>
                </div>
              </div>
            </div>
          </div>
          
          <div class="col-lg-4">
            <div class="row">
              <div class="col-6">
                
              </div>
              {% if posts.user == user %}
              <div class="col-6">
                <a href="" class="btn btn-block btn-primary btn-md">Apply Now</a>
              </div>
              {% else %}{% if user.is_authenticated %}
              <div class="col-6">
                <a href="#" class="btn btn-block btn-primary btn-md"data-toggle="modal" data-target="#ApplicationForm">Apply Now</a>
              </div>
              
              {% else %}
              <div class="col-6">
                <a href="" class="btn btn-block btn-primary btn-md">Apply Now</a>
              </div>
             {% endif %} {% endif %}
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-8">
            <div class="mb-5">
              <br>
              <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-align-left mr-3"></span>รายละเอียดงาน</h3>
              <p>{{ posts.description}} </p>
            </div>

            <div class="mb-5">
              <br>
              <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-align-left mr-3"></span>คุณสมบัติ</h3>
              <p>{{ posts.requirement}} </p>
            </div>

    
            <div class="mb-5">
              <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-rocket mr-3"></span>เกี่ยวกับบริษัท</h3>
              <ul class="list-unstyled m-0 p-0">{% if posts.user == user %}
                <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>{{user.companyprofile.company_detail}}</span></li>
                {%else %}
                <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>{{posts.user.companyprofile.company_detail}}</span></li>
                {% endif %}
              </ul>
            </div>

            <div class="mb-5">
              <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-turned_in mr-3"></span>สวัสดิการบริษัท</h3>
              <ul class="list-unstyled m-0 p-0">{% if posts.user == user %}
                <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>{{user.companyprofile.benifit}}</span></li>
              {%else %} 
                <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>{{posts.user.companyprofile.benifit}}</span></li>
              {% endif %}
              </ul>
            </div>

            <div class="mb-5">
              <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-turned_in mr-3"></span>ช่องทางการติดต่อ</h3>
              <ul class="list-unstyled m-0 p-0">{% if posts.user == user %}
                <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>{{user.companyprofile.contact}}</span></li>
              {%else %} 
                <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>{{posts.user.companyprofile.contact}}</span></li>
              {% endif %}
              </ul>
            </div>

            
            <div class="mb-5">
              <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-turned_in mr-3"></span>ที่อยู่บริษัท</h3>
              <ul class="list-unstyled m-0 p-0">{% if posts.user == user %}
                <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>{{user.companyprofile.company_address}}</span></li>
              {%else %} 
                <li class="d-flex align-items-start mb-2"><span class="icon-check_circle mr-2 text-muted"></span><span>{{posts.user.companyprofile.company_address}}</span></li>
              {% endif %}
              </ul>
            </div>

          </div>
          <div class="col-lg-4">
            <div class="bg-light p-3 border rounded mb-4">
              <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Job Summary</h3>
              <ul class="list-unstyled pl-3 mb-0">
                <li class="mb-2"><strong class="text-black">Published on:</strong> {{ posts.date_posted|date:"F d, Y"}}</li>
                <li class="mb-2"><strong class="text-black">Vacancy:</strong> {{posts.vacancy}}</li>
                <li class="mb-2"><strong class="text-black">Employment Status:</strong> {{posts.type_job}}</li>
                <li class="mb-2"><strong class="text-black">Job Location:</strong>{{posts.location}}</li>
                <li class="mb-2"><strong class="text-black">Salary:</strong> {{posts.salary}}</li>
                <li class="mb-2"><strong class="text-black">Gender:</strong> {{posts.gender}}</li>
                <li class="mb-2"><strong class="text-black">บัตรตัวแทนบริษัท</strong></li>
                {% if posts.user == user %}
                <img class="border p-1 d-inline-block rounded" src="{{user.companyprofile.prove.url}}" width="250" height="160">
                {%else %} 
                <img class="border p-1 d-inline-block rounded" src="{{posts.user.companyprofile.prove.url}}" width="250" height="160">
                {% endif %}
              </ul>
            </div>
 
  {% if posts.user.id == user.id %}
      <div class="bg-light p-3 border rounded">
          <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Applicants
          <a href="{% url 'post:list_app' posts.id %}" class="btn btn-primary btn-sm">View</a></h3>
            {% if posts.post %}
              {% for applicant in posts.post.all %}
              <div class="px-3">
                <img src="{{ applicant.applicant.profile.image.url }}" style="height:32px; width:32px;"/></a>
                <small class="text-muted">{{ applicant.applicant.first_name }} {{ applicant.applicant.last_name }}</small>
              </div>
              {% endfor %}
            {% else %}
              <div class="px-3">
                <small class="text-muted">No Applicants</small>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% else %}
  </section>
    <div class="modal fade" id="ApplicationForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Application Form</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" encytpe="multipart/form-data">
                    {% csrf_token %}
                   <p>รายละเอียดเพิ่มเติม(เช่น ผลงาน,ประสบการณ์,งานอดิเรก){{ form.description }}</p>
                  <p>ช่องทางการติดต่อ(เบอร์โทร,Facebook,Line){{ form.contact_app }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-dark" >Apply</button>
                </form>
            </div>
            </div>
        </div>
    </div>
  {% endif %}
</body>
</html>
{% endblock %}